helper-create-vm-array-cmd() {
  index=0; for net in "${VM_NET[@]}"; do [[ -n "$net" ]] || break; net=$([[ "$net" == "-" ]] && echo "model=${VM_NETHW:-e1000}" || echo "$net"); net=$([[ "$net" != *"model="* ]] && echo "model=${VM_NETHW:-e1000}," || echo "")$net$([[ "$net" != *"bridge="* && -n "$VM_NETWORK_BRIDGE" ]] && echo ",bridge=$VM_NETWORK_BRIDGE")$([[ "$net" != *"firewall="* ]] && echo ",firewall=0")$([[ "$net" != *"macaddr="* ]] && echo ",macaddr=DE:AD:BE:EF:$(hexdump -n2 -e '/1 ":%02X"' /dev/urandom'):$(hexdump -n1 -e '/1 ":%02X"' /dev/urandom')")$([[ "$net" != *"tag="* && -n "$VM_NET_TAG" ]] && echo ",tag=$VM_NET_TAG")$([[ "$net" != *"link_down="* && -n "$VM_NET_STATUS" ]] && echo ",link_down=$VM_NET_STATUS"); CMD+=" --net${index} $net"; ((index++)); done
  index=0; for pci in "${VM_PCI[@]}"; do [[ -n "$pci" ]] && CMD+=" --hostpci${index} $pci" && ((index++)); done
  index=0; for usb in "${VM_USB[@]}"; do [[ -n "$usb" ]] && CMD+=" --usb${index} $usb" && ((index++)); done
  index=0; for serial in "${VM_SERIAL[@]}"; do [[ -n "$serial" ]] && CMD+=" --serial${index} $serial" && ((index++)); done
  index=0; for parallel in "${VM_PARALLEL[@]}"; do [[ -n "$parallel" ]] && CMD+=" --parallel${index} $parallel" && ((index++)); done
  index=0; for scsi in "${VM_SCSI[@]}"; do [[ -n "$scsi" && "$index" -lt 31 ]] || break; scsi=$([[ "$scsi" =~ ^[0-9]+$ ]] && echo "$VM_STORAGE_DISK:$scsi" || [[ "$scsi" == "-" ]] && echo "$VM_STORAGE_DISK:32" || [[ "$scsi" != *":"* ]] && echo "$VM_STORAGE_DISK:$scsi" || echo "$scsi"); [[ "$scsi" != *"backup="* ]] && scsi+=",backup=0"; [[ "$scsi" != *"cache="* ]] && scsi+=",cache=writeback"; [[ "$scsi" != *"discard="* ]] && scsi+=",discard=on"; [[ "$scsi" != *"media=cdrom"* && "$scsi" != *"iothread="* ]] && scsi+=",iothread=1"; CMD+=" --scsi${index} $scsi"; ((index++)); done
  index=0; for sata in "${VM_SATA[@]}"; do [[ -n "$sata" && "$index" -lt 6 ]] || break; sata=$([[ "$sata" =~ ^[0-9]+$ ]] && echo "$VM_STORAGE_DISK:$sata" || [[ "$sata" == "-" ]] && echo "$VM_STORAGE_DISK:32" || [[ "$sata" != *":"* ]] && echo "$VM_STORAGE_DISK:$sata" || echo "$sata"); [[ "$sata" != *"backup="* ]] && sata+=",backup=0"; [[ "$sata" != *"cache="* ]] && sata+=",cache=writeback"; [[ "$sata" != *"discard="* ]] && sata+=",discard=on"; [[ "$sata" != *"media=cdrom"* && "$sata" != *"iothread="* ]] && sata+=",iothread=1"; CMD+=" --sata${index} $sata"; ((index++)); done
  index=0; for ide in "${VM_IDE[@]}"; do [[ -n "$VM_CDROM" && "$index" -eq 2 ]] && ((index++)); [[ -n "$ide" && "$index" -lt 3 ]] || break; ide=$([[ "$ide" =~ ^[0-9]+$ ]] && echo "$VM_STORAGE_DISK:$ide" || [[ "$ide" == "-" ]] && echo "$VM_STORAGE_DISK:32" || [[ "$ide" != *":"* ]] && echo "$VM_STORAGE_DISK:$ide" || echo "$ide"); [[ "$ide" != *"backup="* ]] && ide+=",backup=0"; [[ "$ide" != *"cache="* ]] && ide+=",cache=writeback"; [[ "$ide" != *"discard="* ]] && ide+=",discard=on"; [[ "$ide" != *"media=cdrom"* && "$ide" != *"iothread="* ]] && ide+=",iothread=1"; CMD+=" --ide${index} $ide"; ((index++)); done
  index=0; for nvme in "${VM_NVME[@]}"; do [[ -n "$nvme" && "$index" -lt 31 ]] || break; nvme=$([[ "$nvme" =~ ^[0-9]+$ ]] && echo "$VM_STORAGE_DISK:$nvme" || [[ "$nvme" == "-" ]] && echo "$VM_STORAGE_DISK:32" || [[ "$nvme" != *":"* ]] && echo "$VM_STORAGE_DISK:$nvme" || echo "$nvme"); [[ "$nvme" != *"backup="* ]] && nvme+=",backup=0"; [[ "$nvme" != *"cache="* ]] && nvme+=",cache=writeback"; [[ "$nvme" != *"discard="* ]] && nvme+=",discard=on"; [[ "$nvme" != *"media=cdrom"* && "$nvme" != *"iothread="* ]] && nvme+=",iothread=1"; CMD+=" --nvme${index} $nvme"; ((index++)); done
  index=0; for rng in "${VM_RNG[@]}"; do [[ -n "$rng" && "$index" -lt 1 ]] || break; [[ "$rng" == "-" || "$rng" != *"source="* ]] && rng="source=/dev/urandom$rng"; [[ "$rng" != *"max_bytes="* && -n "$VM_RNG_MAX" ]] && rng+=",max_bytes=$VM_RNG_MAX"; [[ "$rng" != *"period="* && -n "$VM_RNG_PERIOD" ]] && rng+=",period=$VM_RNG_PERIOD"; CMD+=" --rng${index} $rng"; ((index++)); done
  index=0; for audio in "${VM_AUDIO[@]}"; do [[ -n "$audio" && "$index" -lt 1 ]] || break; [[ "$audio" == "-" || "$audio" == "ich9-intel-hda" || "$audio" == "ich9" || "$audio" != *"device="* ]] && audio="device=ich9-intel-hda$audio" || [[ "$audio" == "intel-hda" || "$audio" == "hda" ]] && audio="device=intel-hda$audio" || [[ "$audio" == "AC97" || "$audio" == "ac97" ]] && audio="device=AC97$audio"; [[ "$audio" != *"driver="* ]] && audio+=$([[ "$VM_SPICE" == "1" ]] && echo ",driver=spice" || echo ",driver=none"); CMD+=" --audio${index} $audio"; ((index++)); done
}