helper-create-vm-parse-argument() { 
    while [[ $# -gt 0 ]]; do 
        case "$1" in 
			acpi)           VM_ACPI=1; shift ;; 
			addaudio)       VM_AUDIO+=("$2"); shift 2 ;; 
			addide)         [[ "${#VM_IDE[@]}" -lt 5 ]] && VM_IDE+=("$2"); shift ;; 
			addnet)         VM_NET+=("$2"); shift 2 ;; 
			addnvme)        [[ "${#VM_NVME[@]}" -lt 31 ]] && VM_NVME+=("$2"); shift ;; 
			addparallel) 	[[ "${#VM_PARALLEL[@]}" -lt 5 ]] && VM_PARALLEL+=("socket"); shift ;;  
			addrng)         VM_RNG+=("$2"); shift 2 ;; 
			addsata)        [[ "${#VM_SATA[@]}" -lt 7 ]] && VM_SATA+=("$2"); shift ;; 
			addscsi|adddisk) [[ "${#VM_SCSI[@]}" -lt 31 ]] && VM_SCSI+=("$2"); shift ;;  
			addserial) 		[[ "${#VM_SERIAL[@]}" -lt 5 ]] && VM_SERIAL+=("socket"); shift ;;  
			addusb)         VM_USB+=("$2"); shift 2 ;; 
			agent)          VM_AGENT=1; shift ;; 
			arch)           VM_ARCH="$2"; shift 2 ;; 
			args)			VM_ARGS="$2"; shift 2 ;; 
			audio)          VM_AUDIO="device=ich9-intel-hda,driver=spice"; shift ;; 
			autostart)      VM_ONBOOT=1; shift 2 ;; 
			balloon)		VM_BALLOON=1; shift ;; 
			bios) 			VM_BIOS="seabios"; VM_MACHINE="i440fx"; VM_NO_EFIDISK=1; shift ;; 
			boot)           VM_BOOT_ORDER="$2"; shift 2 ;; 
			bridge)			VM_NETWORK_BRIDGE="$2"; shift 2 ;; 
			bwlimit)		VM_BWLIMIT="$2"; shift 2 ;; 
			cdrom)       	VM_CDROM="$2"; shift 2 ;; 
			clearaudio)		VM_AUDIO+=(); shift ;; 
			clearcdrom)     VM_CDROM=""; shift ;; 
			cleardisk)      VM_DISK=(); shift ;; 
			clearide)		VM_IDE+=(); shift ;; 
			clearnet)       VM_NET=(); shift ;; 
			clearnvme)		VM_NVME+=(); shift ;; 
			clearparallel)  VM_PARALLEL=(); shift ;; 
			clearpci)       VM_PCI=(); shift ;; 
			clearrng)		VM_RNG+=(); shift ;; 
			clearsata)		VM_SATA+=(); shift ;; 
			clearscsi)		VM_SCSI+=(); shift ;; 
			clearserial)    VM_SERIAL=(); shift ;; 
			clearusb)       VM_USB=(); shift ;; 
			cloudinit)      VM_CLOUDINIT=1; shift ;; 
			computername)	VM_COMPUTERNAME="$2"; shift 2 ;; 
			cores)          VM_CORES="$2"; shift 2 ;; 
			cpu)            VM_CPU="$2"; shift 2 ;; 
			addpci)         VM_PCI+=("$2"); shift 2 ;; 
			description)    VM_DESCRIPTION="$2"; shift 2 ;; 
			disksize)       VM_DISK_SIZE="$2"; shift 2 ;; 
			disktype)       VM_DISK_TYPE="$2"; shift 2 ;; 
			dns)            VM_NAMESERVER="$2"; shift 2 ;; 
			efi) 			VM_BIOS="ovmf"; VM_MACHINE="q35"; VM_NO_EFIDISK=0; shift ;; 
			freeze)			VM_FREEZE=1; shift ;; 
			hookscript)     VM_HOOKSCRIPT="$2"; shift 2 ;; 
			hostpci)        VM_HOSTPCI="$2"; shift 2 ;; 
			hugepages)      VM_HUGEPAGES=1; shift ;; 
			isnttemplate)	VM_ISTEMPLATE=0; shift ;;
			istemplate)		VM_ISTEMPLATE=1; shift ;;
			localtime)		VM_LOCALTIME=1; shift ;; 
			localtime)      VM_LOCALTIME=1; shift ;; 
			machine) 		VM_MACHINE="$2" && shift 2 ;; 
			machinever)     VM_MACHINE_VER="$2"; shift 2 ;; 
			nameserver)     VM_NAMESERVER="$2"; shift 2 ;; 
			netboot)        VM_NETBOOT=1; shift ;; 
			nethw)			VM_NETHW="$2"; shift 2 ;; 
			netoff)			VM_NET_STATUS=0; shift ;;
			neton)			VM_NET_STATUS=1; shift ;;
			nettag)			VM_NET_TAG="$2"; shift 2 ;; 
			noacpi)         VM_ACPI=0; shift ;; 
			noagent)        VM_AGENT=0; shift ;; 
			noaudio)        VM_AUDIO=""; shift ;; 
			noautostart)	VM_ONBOOT=0; shift 2 ;; 
			noballoon)		VM_BALLOON=0; shift ;; 
			noefidisk)		VM_NO_EFIDISK=1; shift ;;
			nohugepages)	VM_HUGEPAGES=0; shift ;; 
			nokvm)          VM_KVM=0; shift ;; 
			kvm)          	VM_KVM=1; shift ;; 
			nolocaltime)	VM_LOCALTIME=0; shift ;; 
			nonuma)         VM_NUMA=0; shift 2 ;; 
			nospicefolder)	VM_SPICEFOLDER=0; shift ;;
			nostart)		VM_START=0; shift ;; 
			nowafg)			VM_WAFG=""; shift ;; 
			numa)           VM_NUMA=1; shift 2 ;; 
			os)             VM_OS_TYPE="$2"; shift 2 ;; 
			rng)            VM_RNG="$2"; shift 2 ;; 
			rngmax)			VM_RNG_MAX="$2"; shift 2 ;; 
			rngperiod)      VM_RNG_PERIOD="$2"; shift 2 ;; 
			scsihw)			VM_SCSIHW="$2"; shift 2 ;; 
			searchdomain)   VM_SEARCHDOMAIN="$2"; shift 2 ;; 
			sharedmemory)   VM_IVSHMEM="$2"; shift 2 ;; 
			smbios)         VM_SMBIOS="$2"; shift 2 ;; 
			sockets)        VM_SOCKETS="$2"; shift 2 ;; 
			spice) 			VM_SPICE=1; VM_VGA="qxl"; [ -z "$VM_AUDIO" ] && VM_AUDIO="device=ich9-intel-hda,driver=spice"; shift ;; 
			spiceenh) 		VM_SPICE=1; VM_SPICEFOLDER=0; VM_SPICESTREAM="all"; VM_VGA="qxl"; [ -z "$VM_AUDIO" ] && VM_AUDIO="device=ich9-intel-hda,driver=spice"; shift ;; 
			spiceflt) 		VM_SPICE=1; VM_SPICEFOLDER=0; VM_SPICESTREAM="filter"; VM_VGA="qxl"; [ -z "$VM_AUDIO" ] && VM_AUDIO="device=ich9-intel-hda,driver=spice"; shift ;; 
			spicefolder)	VM_SPICEFOLDER=1; shift ;;
			spicefull) 		VM_SPICE=1; VM_SPICEFOLDER=1; VM_SPICESTREAM="all"; VM_VGA="qxl"; [ -z "$VM_AUDIO" ] && VM_AUDIO="device=ich9-intel-hda,driver=spice"; shift ;; 
			spicemin) 		VM_SPICE=1; VM_SPICEFOLDER=0; VM_SPICESTREAM="off"; VM_VGA="qxl"; shift ;; 
			spicestream)	VM_SPICESTREAM="$2"; shift 2 ;; 
			spicestreamall) VM_SPICESTREAM="all"; shift ;;
			spicestreamfilter) VM_SPICESTREAM="filter"; shift ;;
			spicestreamnone) VM_SPICESTREAM="none"; shift ;;
			ssd)            VM_SSD=1; shift ;; 
			sshkeys)        VM_SSHKEYS="$2"; shift 2 ;; 
			start)			VM_START=1; shift ;; 
			tags)           VM_TAGS="$2"; shift 2 ;; 
			template)       VM_ISTEMPLATE="$2"; shift 2;; 
			vcpus)          VM_VCPUS="$2"; shift 2 ;; 
			wafg)    		VM_WAFG="$2"; shift 2 ;; 
			winsettings)    VM_WINDOWS_SETTINGS="$2"; shift 2 ;; 
            *) 
                echo "Unknown argument: $1"; 
                exit 1 
                ;; 
        esac 
    done 
}