helper-cmd-createw10vm() {
  # Build the base command
	local CMD="qm create $VM_ID"
	[[ -z "$VM_MACHINE" && -z "$VM_MACHINE_VER" ]] && CMD+=" --machine q35" || [[ "$VM_MACHINE" == "q35" && -z "$VM_MACHINE_VER" ]] && CMD+=" --machine q35" || [[ "$VM_MACHINE" == "q35" && -n "$VM_MACHINE_VER" ]] && CMD+=" --machine pc-q35-$VM_MACHINE_VER" || { [[ "$VM_MACHINE" =~ 440 || "$VM_MACHINE" == "pc" ]] && [[ -n "$VM_MACHINE_VER" ]] && CMD+=" --machine pc-$VM_MACHINE_VER"; } || { [[ "$VM_MACHINE" != "q35" && ! "$VM_MACHINE" =~ 440 && "$VM_MACHINE" != "pc" ]] && CMD+=" --machine pc-$VM_MACHINE-$VM_MACHINE_VER"; }
	[[ "$VM_NO_EFIDISK" != "1" ]] && CMD+=" --efidisk0 $VM_STORAGE_DISK:0$( [[ -n "$VM_EFIDISK_SIZE" ]] && echo ",efitype=$VM_EFIDISK_SIZE" )$( [[ -n "$VM_PRE_ENROLL_KEYS" ]] && echo ",pre-enrolled-keys=$([[ "$VM_PRE_ENROLL_KEYS" == "1" ]] && echo 1 || echo 0)" )"
	[[ -n "$VM_ACPI" ]]           && CMD+=" --acpi $VM_ACPI"
	[[ -n "$VM_AGENT" ]]          && CMD+=" --agent $VM_AGENT"
	[[ -n "$VM_ARCH" ]]           && CMD+=" --arch $VM_ARCH"
	[[ -n "$VM_ARGS" ]]           && CMD+=" --args \"$VM_ARGS\""
	[[ -n "$VM_AUDIO" ]]          && CMD+=" --audio0 $VM_AUDIO"
	[[ -n "$VM_BALLOON" ]]        && CMD+=" --balloon $VM_BALLOON"
	[[ -n "$VM_BIOS" ]]      	  && CMD+=" --bios \"$VM_BIOS\""
	[[ -n "$VM_BOOTORDER" ]]      && CMD+=" --boot \"$VM_BOOTORDER\""
	[[ -n "$VM_BWLIMIT" ]]        && CMD+=" --bwlimit $VM_BWLIMIT"
	[[ -n "$VM_CDROM" ]]		  && CMD+=" --cdrom $VM_CDROM"
	[[ -n "$VM_CORES" ]]     	  && CMD+=" --cores \"$VM_CORES\""
	[[ -n "$VM_FREEZE" ]]         && CMD+=" --freeze $VM_FREEZE"
	[[ -n "$VM_HOOKSCRIPT" ]]     && CMD+=" --hookscript $VM_HOOKSCRIPT"
	[[ -n "$VM_HOSTPCI" ]]        && CMD+=" --hostpci0 $VM_HOSTPCI"
	[[ -n "$VM_HUGEPAGES" ]]      && CMD+=" --hugepages $VM_HUGEPAGES"
	[[ -n "$VM_ISTEMPLATE" ]]     && CMD+=" --template $VM_ISTEMPLATE"
	[[ -n "$VM_IVSHMEM" ]]        && CMD+=" --ivshmem size=$VM_IVSHMEM"
	[[ -n "$VM_KEEPPAGES" ]] 	  && CMD+=" --keephugepages $VM_KEEPPAGES" || [[ -n "$VM_HUGEPAGES" ]] && CMD+=" --keephugepages 1"
	[[ -n "$VM_KVM" ]]            && CMD+=" --kvm $VM_KVM"
	[[ -n "$VM_LOCALTIME" ]]      && CMD+=" --localtime $VM_LOCALTIME"
	[[ -n "$VM_MEMORY" ]]    	  && CMD+=" --memory \"$VM_MEMORY\""
	[[ -n "$VM_NAME" ]]      	  && CMD+=" --name \"$VM_NAME\""
	[[ -n "$VM_NAMESERVER" ]]     && CMD+=" --nameserver $VM_NAMESERVER"
	[[ -n "$VM_NUMA" ]]      	  && CMD+=" --numa \"$VM_NUMA\""
	[[ -n "$VM_ONBOOT" ]]         && CMD+=" --onboot $VM_ONBOOT"
	[[ -n "$VM_OS_TYPE" ]]        && CMD+=" --ostype $VM_OS_TYPE"
	[[ -n "$VM_RNG" ]]            && CMD+=" --rng0 $VM_RNG"
	[[ -n "$VM_SCSIHW" ]]         && CMD+=" --scsihw $VM_SCSIHW"
	[[ -n "$VM_SEARCHDOMAIN" ]]   && CMD+=" --searchdomain $VM_SEARCHDOMAIN"
	[[ -n "$VM_SMBIOS" ]]         && CMD+=" --smbios1 $VM_SMBIOS"
	[[ -n "$VM_SOCKETS" ]]   	  && CMD+=" --sockets \"$VM_SOCKETS\""
	[[ -n "$VM_SPICE_ENH" ]]      && CMD+=" --spice_enhancements $VM_SPICE_ENH"
	[[ -n "$VM_SSHKEYS" ]]        && CMD+=" --sshkeys $VM_SSHKEYS"
	[[ -n "$VM_START" ]]          && CMD+=" --start $VM_START"
	[[ -n "$VM_STARTDATE" ]]      && CMD+=" --startdate $VM_STARTDATE"
	[[ -n "$VM_TAGS" ]]           && CMD+=" --tags $VM_TAGS"
	[[ -n "$VM_TPMSTATE" ]]       && CMD+=" --tpmstate0 $VM_TPMSTATE"

  echo "$CMD"
}