# https://admx.help/HKLM/Software/Microsoft/Windows/CurrentVersion/Policies/Explorer
windows-settings-commands() {
    while [ "$#" -gt 0 ]; do
        setting="$1"
        case "$setting" in
			debugspc2) windows-shell-setup-add-specialcommands 'cmd /c "echo "%date% %time%" >> "c:\spcdebug.txt" & pause"' "Debug time to debug.txt" true ;;
			debugspc) windows-shell-setup-add-specialcommands 'cmd /c "echo "%date% %time%" >> "%TMP%\spcdebug.txt""' "Debug time to debug.txt" ;;
			debug) windows-shell-setup-add-firstlogoncommands 'cmd /c "echo "%date% %time%" >> "%TMP%\debug.txt""' "Debug time to debug.txt" ;;
			debugmsg) windows-shell-setup-add-firstlogoncommands 'cmd /c "echo "%date% %time% '$2' >> "%TMP%\debug.txt""' "Debug message $2 to debug.txt"; shift ;;
			writetmpfile) windows-shell-setup-add-firstlogoncommands 'cmd /c "echo "'$2'" > %TMP%\'$3'""' "Write text to tmp file $3"; shift ;;
			writefile) windows-shell-setup-add-firstlogoncommands 'cmd /c "echo "'$2'" > '$3'""' "Write text to tmp file $3"; shift 2 ;;
			appendfile) windows-shell-setup-add-firstlogoncommands 'cmd /c "echo "'$2'" >> '$3'""' "Write text to $3"; shift 2 ;;
			addregstr) windows-shell-setup-add-firstlogoncommands 'reg add "'$2'" /v '$3' /t REG_SZ /d "'$4'" /f' "Add registery string $2\\$3 $4"; shift 3 ;;
			addregdwd) windows-shell-setup-add-firstlogoncommands 'reg add "'$2'" /v '$3' /t REG_DWORD /d "'$4'" /f' "Add registery dword $2\\$3 $4"; shift 3 ;;
			addregqwd) windows-shell-setup-add-firstlogoncommands 'reg add "'$2'" /v '$3' /t REG_QWORD /d "'$4'" /f' "Add registery qword $2\\$3 $4"; shift 3 ;;
			addregbin) windows-shell-setup-add-firstlogoncommands 'reg add "'$2'" /v '$3' /t REG_BINARY /d "'$4'" /f' "Add registery binary $2\\$3 $4"; shift 3 ;;
			addregmstr) windows-shell-setup-add-firstlogoncommands 'reg add "'$2'" /v '$3' /t REG_MULTI_SZ /d "'$4'" /f' "Add registery multi string $2\\$3 $4"; shift 3 ;;
			addregxstr) windows-shell-setup-add-firstlogoncommands 'reg add "'$2'" /v '$3' /t REG_EXPAND_SZ /d "'$4'" /f' "Add registery expand string $2\\$3 $4"; shift 3 ;;
			addregnone) windows-shell-setup-add-firstlogoncommands 'reg add "'$2'" /v '$3' /t REG_NONE /d "'$4'" /f' "Add registery none $2\\$3 $4"; shift 3 ;;
			addtask) windows-shell-setup-add-firstlogoncommands-addtask "$2" "$3" ; shift 2;; 
			test) windows-shell-setup-add-firstlogoncommands 'echo test '$2' > %TMP%\test'$2'.txt' "This is test #$2" ; shift ;;
			test2) windows-shell-setup-add-firstlogoncommands 'copy c:\windows\notepad.exe c:\users\user\desktop\test.notepad.exe' "This is copy notepad test" ;;
			test3) windows-shell-setup-add-firstlogoncommands 'copy NUL c:\users\user\desktop\test.txt' "This is copy notepad test.txt" ;;
			test4) windows-shell-setup-add-firstlogoncommands 'c:\windows\notepad.exe' "Run notepad.exe" ;;
			test5) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\TestCompany" /v TestValue /t REG_SZ /d "Success" /f' "Creating a test registry key" ;;
			test6) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\TestCompany2" /v TestValue /t REG_SZ /d "Success2" /f' "Creating a test registry key2" ;;
			test7) windows-shell-setup-add-firstlogoncommands 'cmd /c "echo test '$2' > %TMP%\test'$2'.txt"' "This is test #$2" ; shift ;;
			ControlPanelCategoryView) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel" /v StartupPage /t REG_DWORD /d 0 /f' "Control Panel Category View" ;;
			ControlPanelClassicView) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel" /v StartupPage /t REG_DWORD /d 1 /f' "Control Panel Classic View" ;;
			ControlPanelLargeIconSize) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel" /v AllItemsIconView /t REG_DWORD /d 0 /f' "Control Panel Large Icon Size" ;;
			ControlPanelSmallIconSize) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel" /v AllItemsIconView /t REG_DWORD /d 1 /f' "Control Panel Small Icon Size" ;;
			PasswordDontExpires) windows-shell-setup-add-firstlogoncommands 'cmd /c "wmic useraccount where name="'$username'" set PasswordExpires=false"' "Password Never Expires" ;;
			PasswordExpires) windows-shell-setup-add-firstlogoncommands 'cmd /c "wmic useraccount where name="'$username'" set PasswordExpires=true"' "Password Expires" ;;
            AddThisPCDesktop) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}" /t REG_DWORD /d 0 /f' 'Add This PC icon to desktop' ;;
            AddThisPCDesktopAllUsers) windows-shell-setup-add-firstlogoncommands 'cmd /c "reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}" /t REG_DWORD /d 0 /f & reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\ClassicStartMenu" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}" /t REG_DWORD /d 0 /f"' 'Add This PC icon to desktop for all users' ;;
            AddUsersFilesIconAllUsers) windows-shell-setup-add-firstlogoncommands 'cmd /c "reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{59031a47-3f72-44a7-89c5-5595fe6b30ee}" /t REG_DWORD /d 0 /f & reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\ClassicStartMenu" /v "{59031a47-3f72-44a7-89c5-5595fe6b30ee}" /t REG_DWORD /d 0 /f"' 'Add Users files icon to desktop for all users' ;;
            AllowConnectingSharesWithoutPassword) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v AllowInsecureGuestAuth /t REG_DWORD /d 1 /f' 'Allow connecting to shares without passwords' ;;
            DeleteTaskbarPinnedApps) windows-shell-setup-add-firstlogoncommands 'reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband" /f' 'Delete pinned apps in taskbar' ;;
            DisableHibernation) windows-shell-setup-add-firstlogoncommands 'powercfg.exe /hibernate off' 'Disable hibernation' ;;
            DisableLockScreen) windows-shell-setup-add-firstlogoncommands 'reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows" /v NoLockScreen /t REG_DWORD /d 1 /f' 'Disable lock screen' ;;
            DisableLoginAfterSleep) windows-shell-setup-add-firstlogoncommands 'cmd /c "powercfg /setdcvalueindex SCHEME_CURRENT SUB_NONE CONSOLELOCK 0 & powercfg /setacvalueindex SCHEME_CURRENT SUB_NONE CONSOLELOCK 0"' 'Disable login after sleep' ;;
            DisableMeetNow) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v HideSCAMeetNow /t REG_DWORD /d 1 /f' 'Disable Meet Now for current user' ;;
            DisableMeetNowAllUsers) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v HideSCAMeetNow /t REG_DWORD /d 1 /f' 'Disable Meet Now for all users' ;;
            EnableFilePrinterSharing) windows-shell-setup-add-firstlogoncommands 'netsh advfirewall firewall set rule group="File and Printer Sharing" new enable=Yes' 'Enable File and Printer Sharing' ;;
            EnableGuestAccount) windows-shell-setup-add-firstlogoncommands 'net user Guest /active:yes' 'Enable guest account' ;;
            EnablePowershellScripts) windows-shell-setup-add-firstlogoncommands 'powershell -command Set-ExecutionPolicy Unrestricted -force' 'Allow PowerShell scripts' ;;
            KillEdge) windows-shell-setup-add-firstlogoncommands 'taskkill /IM msedge.exe /F' 'Kill Edge' ;;
            KillOnedrive) windows-shell-setup-add-firstlogoncommands 'taskkill /f /im OneDrive.exe' 'Kill OneDrive' ;;
            RemoveWallpaper) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v WallPaper /t REG_SZ /d "" /f' 'Remove wallpaper' ;;
            SetAppDarkMode) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme /t REG_DWORD /d 0 /f' 'Enable App Dark Mode' ;;
			SetBackgroundDarkGrey) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Control Panel\Colors" /v Background /t REG_SZ /d "20 20 20" /f' 'Set background color to dark grey' ;;
            SetSystemDarkMode) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f' 'Enable System Dark Mode' ;;
            Show24HourTime) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\Control Panel\International" /v sShortTime /t REG_SZ /d "HH:mm:ss" /f' 'Show 24-hour time format' ;;
            ShowFileExtensions) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v HideFileExt /t REG_DWORD /d 0 /f' 'Show file extensions for known file types' ;;
            ShowHiddenFiles) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v Hidden /t REG_DWORD /d 1 /f' 'Show hidden files' ;;
            ShowSecondsOnTaskbar) windows-shell-setup-add-firstlogoncommands 'reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowSecondsInSystemClock /t REG_DWORD /d 1 /f' 'Show seconds on taskbar' ;;
            SwitchToHighPerformancePlan) windows-shell-setup-add-firstlogoncommands 'powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c' 'Switch to high performance plan' ;;
            TurnOffCortanaButton) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowCortanaButton /t REG_DWORD /d 0 /f' 'Turn off Cortana button on taskbar' ;;
            TurnOffSearchBox) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" /v SearchboxTaskbarMode /t REG_DWORD /d 0 /f' 'Turn off search box on taskbar' ;;
            TurnOffTaskViewButton) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowTaskViewButton /t REG_DWORD /d 0 /f' 'Turn off Task View button on taskbar' ;;
			DisplayThisPCDesktopStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}"' "Display This PC Desktop Icon Status" ;;
            Display24HourTimeStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKCU\Control Panel\International" /v sShortTime' "Display 24-Hour Time Format Status" ;;
            DisplayAppDarkModeStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme' "Display App Dark Mode Status" ;;
            DisplayBackgroundColor) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_CURRENT_USER\Control Panel\Colors" /v Background' "Display Background Color" ;;
            DisplayControlPanelViewMode) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel" /v StartupPage' "Display current Control Panel View Mode" ;;
            DisplayCortanaButtonStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowCortanaButton' "Display Cortana Button Status" ;;
            DisplayCurrentPowerPlan) windows-shell-setup-add-firstlogoncommands 'powercfg /getactivescheme' "Display Current Power Plan" ;;
            DisplayEdgeRunningStatus) windows-shell-setup-add-firstlogoncommands 'tasklist | findstr /I msedge.exe' "Display Edge Running Status" ;;
            DisplayFilePrinterSharingStatus) windows-shell-setup-add-firstlogoncommands 'netsh advfirewall firewall show rule name="File and Printer Sharing"' "Display File and Printer Sharing Status" ;;
            DisplayGuestAccountStatus) windows-shell-setup-add-firstlogoncommands 'net user Guest | findstr /C:"Account active"' "Display Guest Account Status" ;;
            DisplayHibernationStatus) windows-shell-setup-add-firstlogoncommands 'powercfg /query SCHEME_CURRENT SUB_SLEEP HIBERNATEID' "Display Hibernation Status" ;;
            DisplayInsecureGuestAuthStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v AllowInsecureGuestAuth' "Display Insecure Guest Authentication Status" ;;
            DisplayLockScreenStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKLM\SOFTWARE\Policies\Microsoft\Windows" /v NoLockScreen' "Display Lock Screen Status" ;;
            DisplayLoginAfterSleepStatus) windows-shell-setup-add-firstlogoncommands 'powercfg /query SCHEME_CURRENT SUB_NONE CONSOLELOCK' "Display Login After Sleep Status" ;;
            DisplayMeetNowAllUsersStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v HideSCAMeetNow' "Display Meet Now Status for All Users" ;;
            DisplayMeetNowStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v HideSCAMeetNow' "Display Meet Now Status for Current User" ;;
            DisplayOnedriveRunningStatus) windows-shell-setup-add-firstlogoncommands 'tasklist | findstr /I OneDrive.exe' "Display OneDrive Running Status" ;;
            DisplayPasswordExpirationStatus) windows-shell-setup-add-firstlogoncommands "wmic useraccount where name=\"$username\" get PasswordExpires" "Display current Password Expiration setting" ;;
            DisplayPowershellExecutionPolicy) windows-shell-setup-add-firstlogoncommands 'powershell -command Get-ExecutionPolicy' "Display PowerShell Execution Policy" ;;
            DisplaySearchBoxStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" /v SearchboxTaskbarMode' "Display Search Box Status" ;;
            DisplayShowFileExtensionsSetting) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v HideFileExt' "Display Show File Extensions Status" ;;
            DisplayShowHiddenFilesSetting) windows-shell-setup-add-firstlogoncommands 'reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v Hidden' "Display Show Hidden Files Status" ;;
            DisplayShowSecondsOnTaskbarStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowSecondsInSystemClock' "Display Show Seconds on Taskbar Status" ;;
            DisplaySystemDarkModeStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v SystemUsesLightTheme' "Display System Dark Mode Status" ;;
            DisplayTaskViewButtonStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowTaskViewButton' "Display Task View Button Status" ;;
            DisplayTaskbarPinnedAppsStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband"' "Display Taskbar Pinned Apps Status" ;;
            DisplayThisPCDesktopAllUsersStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}"' "Display This PC Desktop Icon Status for All Users" ;;
            DisplayUsersFilesIconAllUsersStatus) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{59031a47-3f72-44a7-89c5-5595fe6b30ee}"' "Display Users Files Icon Status for All Users" ;;
            DisplayWallpaperPath) windows-shell-setup-add-firstlogoncommands 'reg query "HKEY_CURRENT_USER\Control Panel\Desktop" /v WallPaper' "Display Current Wallpaper Path" ;;
            DisableContentDeliveryManager) windows-shell-setup-add-firstlogoncommands 'cmd /c "reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "SubscribedContent-338388Enabled" /t REG_DWORD /d "0" /f & reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "SubscribedContent-338389Enabled" /t REG_DWORD /d "0" /f & reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "ContentDeliveryAllowed" /t REG_DWORD /d "0" /f & reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "OemPreInstalledAppsEnabled" /t REG_DWORD /d "0" /f & reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "PreInstalledAppsEnabled" /t REG_DWORD /d "0" /f & reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "PreInstalledAppsEverEnabled" /t REG_DWORD /d "0" /f & reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "SilentInstalledAppsEnabled" /t REG_DWORD /d "0" /f & reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "SoftLandingEnabled" /t REG_DWORD /d "0" /f & reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" /v "SubscribedContentEnabled" /t REG_DWORD /d "0" /f & reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\Subscriptions" /f & reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SuggestedApps" /f"' "Disable ContentDeliveryManager" ;;
			TurnOffNewsAndInterest) windows-shell-setup-add-firstlogoncommands 'cmd /c "taskkill /f /im explorer.exe & reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds" /v ShellFeedsTaskbarViewMode /t REG_DWORD /d 2 /f & explorer.exe"' 'Turn off news and interest' ;;
			ShowAllIconsInSystray) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer" /v EnableAutoTray /t REG_DWORD /d 0 /f' 'Show all icons in systray' ;;
			DisableDataCollectionNotifications) windows-shell-setup-add-firstlogoncommands 'reg add HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection /v DisableNotification /t REG_DWORD /d 1 /f' 'Disable Data Collection Notifications' ;;
			UninstallOneDrive) windows-shell-setup-add-firstlogoncommands 'cmd /c "taskkill /im onedrive.exe /f & (IF EXIST "%systemroot%\System32\OneDriveSetup.exe" "%systemroot%\System32\OneDriveSetup.exe" /uninstall) & (IF EXIST "%systemroot%\SysWOW64\OneDriveSetup.exe" "%systemroot%\SysWOW64\OneDriveSetup.exe" /uninstall)"' 'Uninstall onedrive'  ;;
			TurnOffNewsAndInterestv2) windows-shell-setup-add-firstlogoncommands 'cmd /c "reg add "HKLM\SOFTWARE\Microsoft\PolicyManager\default\NewsAndInterests\AllowNewsAndInterests" /v value /t REG_DWORD /d 0 /f & reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds" /v EnableFeeds /t REG_DWORD /d 0 /f"' 'Turn off news and interest v2' ;;
			TurnOffNewsAndInterestv3) windows-shell-setup-add-firstlogoncommands 'cmd /c "schtasks /create /tn "DisableNewsAndInterests" /tr "cmd /c "taskkill /f /im explorer.exe & for /f "usebackq tokens=3 delims= " %A in (`whoami /user /fo list ^| findstr SID`) do ( reg add "HKEY_USERS\%A\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds" /v ShellFeedsTaskbarViewMode /t REG_DWORD /d 2 /f & start explorer.exe & schtasks /delete /tn DisableNewsAndInterests /f" /sc ONLOGON /ru "SYSTEM")""' 'Turn off news and interest v3' ;;
			
			RemoveAppx) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "\"'$2'\" -split \",\" | ForEach-Object { Get-AppxPackage $_ | Remove-AppxPackage; Get-AppxPackage -AllUsers $_ | Remove-AppxPackage; Get-AppxProvisionedPackage -Online | Where-Object { $_.DisplayName -eq $_ } | ForEach-Object { Remove-AppxProvisionedPackage -Online -PackageName $_.PackageName } }"' "Remove appx $2 for all users and provisioning"; shift ;;
			RemoveAppxUser) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "\"'$2'\" -split \",\" | Get-AppxPackage | Remove-AppxPackage"' "Remove appx $2 for user"; shift ;;
			RemoveAppxAllUser) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "\"'$2'\" -split \",\" | ForEach-Object { Get-AppxPackage $_ | Remove-AppxPackage; Get-AppxPackage -AllUsers $_ | Remove-AppxPackage }"' "Remove appx $2 for all users"; shift ;;
			ListUserAppx) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "Get-AppxPackage | Select-Object Name, PackageFullName, InstallLocation, NonRemovable, SignatureKind, Status | Sort-Object NonRemovable, SignatureKind, Name | Format-Table -AutoSize" > "%TMP\list.user.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt""' 'List User Appx' ;;
			ListAllUserAppx) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "Get-AppxPackage -AllUsers | Select-Object Name, PackageFullName, InstallLocation, NonRemovable, SignatureKind, Status | Sort-Object NonRemovable, SignatureKind, Name | Format-Table -AutoSize" > "%TMP\list.all.user.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt""' 'List All User Appx' ;;
			ListProvisionnedAppx) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "Get-AppxProvisionedPackage -Online | Select-Object DisplayName, PackageName, InstallLocation, NonRemovable, SignatureKind, Status | Sort-Object NonRemovable, SignatureKind, DisplayName | Format-Table -AutoSize" > "%TMP\list.provisionned.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt""' 'List Provisionned Appx' ;;
			ListNonUserAppx) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "$CurrentUserApps=(Get-AppxPackage|Select-Object -ExpandProperty PackageFullName);$AllUsersApps=Get-AppxPackage -AllUsers|Where-Object {$_.PackageFullName -and ($CurrentUserApps -notcontains $_.PackageFullName)};$ProvisionedApps=Get-AppxProvisionedPackage -Online|Where-Object {$_ -and ($CurrentUserApps -notcontains $_.PackageName)}|Select-Object @{Name=\"Name\";Expression={$_.DisplayName}},PackageName,InstallLocation,NonRemovable,SignatureKind,Status;$AllUsersApps+$ProvisionedApps|Select-Object Name,PackageFullName,InstallLocation,NonRemovable,SignatureKind,Status|Sort-Object NonRemovable,SignatureKind,Name|Format-Table -AutoSize" > "%TMP\list.nonuser.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt""' 'List NonUser Appx' ;;
			ListProvisionnedOnlyAppx) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "$CurrentUserApps=(Get-AppxPackage|Select-Object -ExpandProperty PackageFullName);$AllUsersApps=(Get-AppxPackage -AllUsers|Select-Object -ExpandProperty PackageFullName);$ProvisionedApps=Get-AppxProvisionedPackage -Online|Where-Object {($_.PackageName -and $CurrentUserApps -notcontains $_.PackageName) -and ($AllUsersApps -notcontains $_.PackageName)}|Select-Object @{Name=\"Name\";Expression={$_.DisplayName}},PackageName,InstallLocation,NonRemovable,SignatureKind,Status;$ProvisionedApps|Sort-Object NonRemovable,SignatureKind,Name|Format-Table -AutoSize" > "%TMP\list.provision.only.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt""' 'List Provisionned Only Appx' ;;
			ListAppxFullReport) windows-shell-setup-add-firstlogoncommands 'cmd /c "powershell -command "Get-AppxPackage | Select-Object Name, PackageFullName, InstallLocation, NonRemovable, SignatureKind, Status | Sort-Object NonRemovable, SignatureKind, Name | Format-Table -AutoSize" > "%TMP\list.user.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt" & powershell -command "Get-AppxPackage -AllUsers | Select-Object Name, PackageFullName, InstallLocation, NonRemovable, SignatureKind, Status | Sort-Object NonRemovable, SignatureKind, Name | Format-Table -AutoSize" > "%TMP\list.all.user.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt" & powershell -command "Get-AppxProvisionedPackage -Online | Select-Object DisplayName, PackageName, InstallLocation, NonRemovable, SignatureKind, Status | Sort-Object NonRemovable, SignatureKind, DisplayName | Format-Table -AutoSize" > "%TMP\list.provisionned.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt" & powershell -command "$CurrentUserApps=(Get-AppxPackage|Select-Object -ExpandProperty PackageFullName);$AllUsersApps=Get-AppxPackage -AllUsers|Where-Object {$_.PackageFullName -and ($CurrentUserApps -notcontains $_.PackageFullName)};$ProvisionedApps=Get-AppxProvisionedPackage -Online|Where-Object {$_ -and ($CurrentUserApps -notcontains $_.PackageName)}|Select-Object @{Name='"'"'Name'"'"';Expression={$_.DisplayName}},PackageName,InstallLocation,NonRemovable,SignatureKind,Status;$AllUsersApps+$ProvisionedApps|Select-Object Name,PackageFullName,InstallLocation,NonRemovable,SignatureKind,Status|Sort-Object NonRemovable,SignatureKind,Name|Format-Table -AutoSize" > "%TMP\list.nonuser.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt" & powershell -command "$CurrentUserApps=(Get-AppxPackage|Select-Object -ExpandProperty PackageFullName);$AllUsersApps=(Get-AppxPackage -AllUsers|Select-Object -ExpandProperty PackageFullName);$ProvisionedApps=Get-AppxProvisionedPackage -Online|Where-Object {($_.PackageName -and $CurrentUserApps -notcontains $_.PackageName) -and ($AllUsersApps -notcontains $_.PackageName)}|Select-Object @{Name='"'"'Name'"'"';Expression={$_.DisplayName}},PackageName,InstallLocation,NonRemovable,SignatureKind,Status;$ProvisionedApps|Sort-Object NonRemovable,SignatureKind,Name|Format-Table -AutoSize" > "%TMP\list.provision.only.appx.%date%.%time:~0,2%h%time:~3,2%m%time:~6,2%.txt" "' 'List appx full report';;
			DeleteEdgeShortcut) windows-shell-setup-add-firstlogoncommands 'cmd /c "(if exist "%public%\desktop\Microsoft Edge.lnk" (del "%public%\desktop\Microsoft Edge.lnk")) & (if exist "%userprofile%\desktop\Microsoft Edge.lnk" (del "%userprofile%\desktop\Microsoft Edge.lnk"))"' 'Delete edge shortcut' ;;
			CreateStartLayoutFile) windows-shell-setup-add-firstlogoncommands 'cmd /c "(echo ^<LayoutModificationTemplate xmlns:defaultlayout=\"http://schemas.microsoft.com/Start/2014/FullDefaultLayout\" xmlns:start=\"http://schemas.microsoft.com/Start/2014/StartLayout\" Version=\"1\" xmlns:taskbar=\"http://schemas.microsoft.com/Start/2014/TaskbarLayout\" xmlns=\"http://schemas.microsoft.com/Start/2014/LayoutModification\"^> & echo     ^<LayoutOptions StartTileGroupCellWidth=\"6\" /^> & echo     ^<DefaultLayoutOverride^> & echo         ^<StartLayoutCollection^> & echo             ^<defaultlayout:StartLayout GroupCellWidth=\"6\" /^> & echo         ^</StartLayoutCollection^> & echo     ^</DefaultLayoutOverride^> & echo ^</LayoutModificationTemplate^>) > C:\Windows\StartMenuLayout.xml"' 'Create start layout file' ;;
			CreateDefaultStartLayoutFile) windows-shell-setup-add-specialcommands 'cmd /c "(echo ^<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification" xmlns:taskbar="http://schemas.microsoft.com/Start/2014/TaskbarLayout"^>& echo   ^<LayoutOptions StartTileGroupCellWidth="6" /^>& echo   ^<DefaultLayoutOverride^>& echo     ^<StartLayoutCollection^>& echo       ^<defaultlayout:StartLayout GroupCellWidth="6" /^>& echo     ^</StartLayoutCollection^>& echo   ^</DefaultLayoutOverride^>& echo   ^<CustomTaskbarLayoutCollection^>& echo     ^<defaultlayout:TaskbarLayout^>& echo       ^<taskbar:TaskbarPinList^>& echo         ^<taskbar:UWA AppUserModelID="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" /^>& echo         ^<taskbar:DesktopApp DesktopApplicationLinkPath="%%APPDATA%%\Microsoft\Windows\Start Menu\Programs\System Tools\File Explorer.lnk" /^>& echo         ^<taskbar:DesktopApp DesktopApplicationLinkPath="C:\Windows\System32\calc.exe" /^>& echo       ^</taskbar:TaskbarPinList^>& echo     ^</defaultlayout:TaskbarLayout^>& echo   ^</CustomTaskbarLayoutCollection^>& echo ^</LayoutModificationTemplate^>) > C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\DefaultLayouts.xml"' 'Create default start layout file' ;;
			DisableScreenSaver) windows-shell-setup-add-firstlogoncommands 'cmd /c "powercfg /change monitor-timeout-ac 0 & powercfg /change monitor-timeout-dc 0"' 'Disable Screen Saver' ;;
			ClearStartMenuTiles) ;;
			SetStartMenuTilesLocked) windows-shell-setup-add-firstlogoncommands 'cmd /c "reg add "HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v LockedStartLayout /t REG_DWORD /d 1 /f & reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v LockedStartLayout /t REG_DWORD /d 1 /f "' 'Set Start Menu Tiles Locked' ;;
			SetStartMenuTilesUnLocked) windows-shell-setup-add-firstlogoncommands 'cmd /c "reg add "HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v LockedStartLayout /t REG_DWORD /d 0 /f & reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v LockedStartLayout /t REG_DWORD /d 0 /f"' 'Set Start Menu Tiles Unlocked' ;;
			ResetStartMenuTiles) windows-shell-setup-add-firstlogoncommands 'powershell -command "Stop-Process -Name explorer -Force; Start-Sleep -s 5; $wshell = New-Object -ComObject wscript.shell; $wshell.SendKeys('"'"'^{ESCAPE}'"'"'); Start-Sleep -s 5; $wshell.SendKeys('"'"'{ESCAPE}'"'"')"' 'Reset Start Menu Tiles' ;;
			SetStartMenuTilesFile) windows-shell-setup-add-firstlogoncommands 'cmd /c "reg add "HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v StartLayoutFile /t REG_SZ /d "C:\Windows\StartMenuLayout.xml" /f & reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v StartLayoutFile /t REG_SZ /d "C:\Windows\StartMenuLayout.xml" /f"' 'Set Start Menu Tiles File' ;;
			MountGuestNetworkShare) windows-shell-setup-add-firstlogoncommands 'runas /user:'$2' "cmd /c net use '$3' '$4' /user:guest"' 'Mount network share' ; shift 3 ;;
			DirectCommand) windows-shell-setup-add-firstlogoncommands  ''$2'' "$3" ; shift 2 ;;
			RunOnce) ;;
			OnLogon) windows-shell-setup-add-firstlogoncommands 'cmd /c schtasks /create /tn "DisableNewsAndInterests" /tr "cmd /c taskkill /f /im explorer.exe & reg add HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds /v ShellFeedsTaskbarViewMode /t REG_DWORD /d 2 /f & start explorer.exe & schtasks /delete /tn DisableNewsAndInterests /f" /sc ONLOGON /ru "%USERNAME%"' 'Turn off news and interest v3' ;;
			AddService) windows-shell-setup-add-firstlogoncommands 'sc create '$3' binPath= "cmd.exe /c '$2' & timeout /T 300" start= auto' '$3' ; shift 2 ;;
			AddOneTimeService) windows-shell-setup-add-firstlogoncommands 'sc create '$3' binPath= "cmd.exe /c '$2' & timeout /T 60 & sc delete MyTestService" start= auto' '$3' ; shift 2 ;;
			DisableScrollForwardInConsole) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\Console" /v TerminalScrolling /t REG_DWORD /d 1 /f' 'Disable scroll forward in console' ;;
			DisableStickyKeys) windows-shell-setup-add-firstlogoncommands 'reg add "HKCU\Control Panel\Accessibility\StickyKeys" /v Flags /t REG_SZ /d 506 /f' 'Disable sticky keys' ;;
			Multicommandtest) windows-shell-setup-add-specialcommands 'cmd /c "reg load "HKU\Default" C:\Users\Default\NTUSER.DAT & reg add "HKU\Default\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f & reg add "HKU\Default\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme /t REG_DWORD /d 0 /f & reg add "HKU\Default\Control Panel\Desktop" /v WallPaper /t REG_SZ /d "" /f & reg unload HKU\Default"' 'multicommand test';;

			#show all icons in systray
			#remove taskview button
			#delete onedrive
			#news and interest still problem
			#screensaver still enabled
			#delete edge desktop shortcut
			#apply all changes to default user (and all users ?)
			#taskbar remove edge, store and mail
			#suppress notification something happened, and we couldn't install a feature
			#suppress notification Your administrator or organisation has set your device's windows diagnostic data setting to: Required
			#suppress notificationSearching for Display Driver
			Clear) windows-shell-setup-clear-firstlogoncommands ;;
            *) echo "Warning: Unknown setting '$setting' will be ignored in (windows-settings-commands)." ;;
        esac
        shift
    done
}